# Generated by Django 4.2.1 on 2023-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키 (자동 증가)')),
                ('username', models.CharField(max_length=32, verbose_name='유저 ID')),
                ('password', models.CharField(max_length=128, verbose_name='유저 암호')),
                ('team', models.CharField(choices=[('danbi', '단비'), ('darae', '다래'), ('blah', '블라'), ('rail', '철로'), ('sloth', '해태'), ('ddang', '땅이'), ('supi', '수피')], default='danbi', max_length=32, verbose_name='소속 팀 이름')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
