# Generated by Django 4.2.1 on 2023-06-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='기본키(자동 증가)')),
                ('refresh_token', models.CharField(default='', max_length=256, verbose_name='발급된 rfresh_token 정보')),
                ('relation_id', models.OneToOneField(db_column='relation_id', on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
            ],
            options={
                'db_table': 'Token',
                'managed': True,
            },
        ),
    ]
