# Generated by Django 4.2.1 on 2023-06-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('platform_app', '0002_alter_subtask_relation_id_alter_subtask_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_user',
            field=models.ForeignKey(db_column='create_user', on_delete=django.db.models.deletion.CASCADE, related_name='task_set', related_query_name='task', to='auth_app.user', verbose_name='업무 생성 유저(외래키)'),
        ),
    ]
